#!/bin/sh

stopContainer() {

	RUNNING=$(docker inspect --format="{{.State.Running}}" $CONTAINER 2> /dev/null)
	if [ $? -eq 1 ] ; then
		echo "$CONTAINER does not exist."
	fi
	if [ "$RUNNING" == "true" ] ; then
		echo "$CONTAINER is running. We stop it"
		docker stop $CONTAINER
	fi

#	GHOST=$(docker inspect --format="{{.State.Ghost}}" $CONTAINER)
#echo "$GHOST"
#	if [ "$GHOST" == "true" ]; then
#		echo "$CONTAINER has been ghosted. We kill it"
#		docker kill $CONTAINER
#	fi
}

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

DOCKER_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-docker-site.conf"

case "$1" in
    purge|remove)

        if [ -e "${DOCKER_SITE_CONF}" ]; then
            rm -f ${DOCKER_SITE_CONF}
        fi

	for x in "$(docker ps -q | xargs docker inspect --format '{{.Name}}' $1)"; do 
		echo "$x container will be treated"
		CONTAINER=$(echo "$x" | sed -e "s/\///g")
		stopContainer
		echo "$x container is stopped but not removed"
	done

        service nginx reload
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
